window.PARTYROOM_CONFIG = Object.freeze({
  reviewMode: true,
  businessName: "퓨처스페이스 게임파티룸",
  bookingUrl: "",
  bookingLabel: "네이버 예약",
  phone: "",
  kakaoUrl: "",
  instagramUrl: "",
  address: "경기도 파주시 송학1길 67-21",
  mapUrl: "https://map.naver.com/p/search/%EA%B2%BD%EA%B8%B0%EB%8F%84%20%ED%8C%8C%EC%A3%BC%EC%8B%9C%20%EC%86%A1%ED%95%991%EA%B8%B8%2067-21",
  directions: "건물 1층 가운데 문으로 들어온 뒤 왼쪽 Room 1로 오시면 됩니다. 야당역에서 도보 약 1분 거리입니다.",
  hours: "24시간 운영",
  price: "",
  capacity: "기준 6인 · 최대 20인 · 6인 초과 시 1인당 1만원 추가",
  parking: "차량 2대 무료주차 가능",
  checkin: "비대면 입실 안내 · 예약 확정 후 이용 방법 전달",
  refund: "당일 취소 환불 불가 · 보증금 10만원",
  rules: "실내 흡연 금지 · 배달·취사·음주 가능 · 미성년자 이용 가능 · 이용 후 분리수거",
  sellingPoints: "야당역 도보 약 1분 · 차량 2대 무료주차 · 최대 20인 이용 가능한 넓은 공간",
  bookingNote: "네이버 예약 링크와 최종 요금표 확인 후 예약 버튼이 활성화됩니다."
});