window.PARTYROOM_CONFIG = Object.freeze({
  reviewMode: false,
  businessName: "퓨처스페이스 게임파티룸",
  bookingUrl: "https://naver.me/FdqhKL45",
  bookingLabel: "네이버 예약하기",
  spacecloudUrl: "https://www.spacecloud.kr/space/77835",
  phone: "0507-1400-7266",
  kakaoUrl: "",
  instagramUrl: "",
  address: "경기도 파주시 송학1길 67-21, 1층",
  mapUrl: "https://naver.me/FdqhKL45",
  directions: "야당역 3번 출구에서 도보 약 1분 거리입니다. 건물 1층 가운데 문으로 들어온 뒤 왼쪽 Room 1로 오시면 됩니다.",
  hours: "24시간 운영 · 낮 11:00~17:00 · 밤 18:30~01:00 · 올데이 11:00~01:00 · 밤샘 추가 시 다음 날 09:00 퇴실",
  price: "낮 10만~18만원 · 밤 12만9천~20만9천원 · 올데이 15만9천~23만9천원 · 밤샘 추가 3만원",
  capacity: "기준 6인 · 최대 20인 · 6인 초과 시 1인당 1만원 추가",
  parking: "건물 주차장 차량 2대 무료 · 시간 제한 없음",
  checkin: "비대면 입실 · 예약 확정 후 이용 방법 전달 · 1층 가운데 문 입장 후 왼쪽 Room 1",
  refund: "당일 취소 환불 불가 · 시설·청소 보증금 10만원 별도 · 퇴실 점검 후 1~3일 내 환급 · 파손·과도한 오염·실내 흡연·정리 미흡·절도 시 차감 또는 미환급",
  rules: "실내 흡연 금지 · 배달·포장음식 가능 · 성인 주류 반입 가능 · 인덕션으로 라면 등 간단 조리 가능 · 퇴실 전 원위치 및 쓰레기 정리 · 미성년자 및 2006년생은 22시까지 이용 · 초등학생은 보호자 동반",
  sellingPoints: "야당역 도보 약 1분 · 30평대 넓은 공간 · 고사양 PC 5대 · 75인치 UHD TV · PS5·Switch 2 · TJ 노래방·JBL 마이크 · 차량 2대 무료주차",
  bookingNote: "현재 예약과 이용은 1호 기준입니다. 군인 인증 시 최종 요금 10% 할인됩니다. 예약창이 닫혀 있어도 네이버 톡톡 또는 전화로 문의해 주세요."
});