window.PARTYROOM_CONFIG = Object.freeze({
  reviewMode: true,
  businessName: "",
  bookingUrl: "",
  bookingLabel: "온라인 예약",
  phone: "",
  kakaoUrl: "",
  instagramUrl: "",
  address: "",
  mapUrl: "",
  directions: "",
  hours: "",
  price: "",
  capacity: "",
  parking: "",
  checkin: "",
  refund: "",
  rules: "",
  sellingPoints: "",
  bookingNote: "운영 정보 확인 후 예약 링크와 상세 안내가 공개됩니다."
});
